# Generated by Django 3.0.3 on 2020-09-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobscanada',
            name='job_id',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='jobscanada',
            name='title',
            field=models.TextField(max_length=1000),
        ),
    ]
