# Generated by Django 3.1.1 on 2020-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_skillset_skilltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobscanada',
            name='job_types',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
