# Generated by Django 3.1.1 on 2020-09-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_jobscanada_job_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='url',
        ),
        migrations.AddField(
            model_name='company',
            name='indeed_company_url',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='monster_company_url',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
